### ISSUE TITLE
TASK [slurm : Install Jetpack Fails

### ISSUE THREAD

**Issue by Montereytony** [jpontvianne/azhop#5]
## Version
Not sure, I cloned https://github.com/jpontvianne/azhop

## In what area(s)?

 /area cyclecloud

## Actual Behavior
273 TASK [slurm : install CycleCloud repo] *****************************************
274 Monday 09 December 2024  13:44:23 -0800 (0:00:00.100)       0:00:25.705 *******
275 ok: [scheduler]
276
277 TASK [slurm : Install Jetpack] *************************************************
278 Monday 09 December 2024  13:44:25 -0800 (0:00:01.655)       0:00:27.360 *******
279 fatal: [scheduler]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from cyclecloud: [Errno 256] No more mirrors to try.\nhttps://packages.microsoft.com/yumrepos/cy    clecloud/repodata/repomd.xml: [Errno 14] curl#6 - \"Could not resolve host: packages.microsoft.com; Unknown error\""}
280
281 PLAY RECAP *********************************************************************
282 scheduler                  : ok=13   changed=1    unreachable=0    failed=1    skipped=42   rescued=0    ignored=0
283
284 Monday 09 December 2024  13:44:27 -0800 (0:00:02.210)       0:00:29.571 *******
285 ===============================================================================
286 slurm ------------------------------------------------------------------ 20.10s
287 wait_for_connection ----------------------------------------------------- 4.03s
288 setup ------------------------------------------------------------------- 3.13s
289 command ----------------------------------------------------------------- 2.05s
290 include_role ------------------------------------------------------------ 0.23s
291 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
292 total ------------------------------------------------------------------ 29.55s

## Steps to Reproduce the Problem
./build -a plan 
./build -a apply 
./create_passwords.sh
./install.sh

No errors uptime the Jetpack install. 

Thanks for looking at this,
Tony

**Comment by Montereytony** [comment]
I was able to ssh into the machine

and entered yum install jetpack8 and notice that it could not find any mirrors, the /etc/resolve.conf was empty, so i added a name server and ran yum install again. Then I saw this:

`Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : jetpack8-8.6.5-3340.x86_64                                                                                                                                                                  1/1







WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- Logging error ---
Traceback (most recent call last):
  File "/opt/cycle/jetpack/system/embedded/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/opt/cycle/jetpack/system/embedded/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/opt/cycle/jetpack/system/embedded/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/opt/cycle/jetpack/system/embedded/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/cycle/jetpack/system/install/install.py", line 243, in <module>
    logger.warning("Status '{}'.  Exiting with non-zero code 1.", result.get("status", "").lower())
Message: "Status '{}'.  Exiting with non-zero code 1."
Arguments: ('error',)
{"status": "Error", "description": "Unexpected error installing Jetpack", "detail": "Traceback (most recent call last):\n  File \"/opt/cycle/jetpack/system/install/install.py\", line 171, in <module>\n    configs = retry_get_current_config()\n  File \"/opt/cycle/jetpack/system/embedded/lib/python3.8/site-packages/jetpack/util/__init__.py\", line 80, in wrapper\n    return f(*args, **kwargs)\n  File \"/opt/cycle/jetpack/system/install/install.py\", line 134, in retry_get_current_config\n    return jetpack.util.get_current_config()\n  File \"/opt/cycle/jetpack/system/embedded/lib/python3.8/site-packages/jetpack/util/__init__.py\", line 590, in get_current_config\n    connection_config = get_connection_config()\n  File \"/opt/cycle/jetpack/system/embedded/lib/python3.8/site-packages/jetpack/util/__init__.py\", line 422, in get_connection_config\n    with open(os.path.join(jetpack_home(), 'config', 'connection.json')) as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/opt/cycle/jetpack/config/connection.json'\n", "recommendation": "Check /opt/cycle/jetpack/logs/install.log for more information", "message": "Could not install Jetpack"}
warning: %post(jetpack8-8.6.5-3340.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package jetpack8-8.6.5-3340.x86_64
  Verifying  : jetpack8-8.6.5-3340.x86_64                                                                                                                                                                  1/1

Installed:
  jetpack8.x86_64 0:8.6.5-3340

Complete!`

Not sure if its good or bad.
